"""empty message

Revision ID: 0aff3e63bfc9
Revises: 5f4da0b53539
Create Date: 2022-08-27 13:51:40.323394

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0aff3e63bfc9'
down_revision = '5f4da0b53539'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('seeking_venue', sa.Boolean(), nullable=False))
    op.drop_column('artist', 'looking_artist')
    op.add_column('show', sa.Column('artist_id', sa.Integer(), nullable=False))
    op.add_column('show', sa.Column('venue_id', sa.Integer(), nullable=False))
    op.add_column('show', sa.Column('start_time', sa.DateTime(), nullable=True))
    op.drop_constraint('show_Artist_ID_fkey', 'show', type_='foreignkey')
    op.drop_constraint('show_Venue_ID_fkey', 'show', type_='foreignkey')
    op.create_foreign_key(None, 'show', 'venue', ['venue_id'], ['id'])
    op.create_foreign_key(None, 'show', 'artist', ['artist_id'], ['id'])
    op.drop_column('show', 'Venue_ID')
    op.drop_column('show', 'Artist_ID')
    op.drop_column('show', 'Start_Time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('Start_Time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('show', sa.Column('Artist_ID', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('show', sa.Column('Venue_ID', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'show', type_='foreignkey')
    op.drop_constraint(None, 'show', type_='foreignkey')
    op.create_foreign_key('show_Venue_ID_fkey', 'show', 'venue', ['Venue_ID'], ['id'])
    op.create_foreign_key('show_Artist_ID_fkey', 'show', 'artist', ['Artist_ID'], ['id'])
    op.drop_column('show', 'start_time')
    op.drop_column('show', 'venue_id')
    op.drop_column('show', 'artist_id')
    op.add_column('artist', sa.Column('looking_artist', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('artist', 'seeking_venue')
    # ### end Alembic commands ###
