"""empty message

Revision ID: 9145a391287a
Revises: 0aff3e63bfc9
Create Date: 2022-08-27 15:26:30.272560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9145a391287a'
down_revision = '0aff3e63bfc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('genres', sa.String(length=50), nullable=False))
    op.drop_column('venue', 'genre')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('genre', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('venue', 'genres')
    # ### end Alembic commands ###
