"""empty message

Revision ID: ac86bc2b0609
Revises: 
Create Date: 2022-08-21 21:47:47.124643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac86bc2b0609'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('website_link', sa.String(length=120), nullable=True))
    op.add_column('Artist', sa.Column('Seeking_Description', sa.String(length=500), nullable=True))
    op.add_column('Artist', sa.Column('Looking_Artist', sa.Boolean(), nullable=False))
    op.add_column('Venue', sa.Column('website_link', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('Seeking_Description', sa.String(length=500), nullable=True))
    op.add_column('Venue', sa.Column('Looking_Venue', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'Looking_Venue')
    op.drop_column('Venue', 'Seeking_Description')
    op.drop_column('Venue', 'website_link')
    op.drop_column('Artist', 'Looking_Artist')
    op.drop_column('Artist', 'Seeking_Description')
    op.drop_column('Artist', 'website_link')
    # ### end Alembic commands ###
