"""empty message

Revision ID: d06339c6d6f7
Revises: aa3a7fca8662
Create Date: 2022-08-22 16:56:20.242748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd06339c6d6f7'
down_revision = 'aa3a7fca8662'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Artist_ID', sa.Integer(), nullable=False),
    sa.Column('Venue_ID', sa.Integer(), nullable=False),
    sa.Column('Start_Time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['Artist_ID'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['Venue_ID'], ['venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('show')
    # ### end Alembic commands ###
