"""empty message

Revision ID: f584416c9868
Revises: b8e7ec301986
Create Date: 2022-08-30 22:24:03.092759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f584416c9868'
down_revision = 'b8e7ec301986'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('seeking_talent', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'seeking_talent')
    # ### end Alembic commands ###
